---
title: "Model AOI"
author: "ROSSyndicate"
date: "2023-07-18"
output: html_document
---
 
```{r setup, echo = FALSE}
packages <- c('tidyverse',
              'sf')

package_installer <- function(x) {
  if (x %in% installed.packages()) {
    print(paste0('{', x ,'} package is already installed.'))
  } else {
    install.packages(x)
    print(paste0('{', x ,'} package has been installed.'))
  }
}

lapply(packages, package_installer)

# point to directories
shp_dir = 'data/aoi/'
```

# Read in shapefiles and create AOI for modeling

The original Superior shapefile:

```{r}
superior = read_sf(file.path(shp_dir, 'NHDPlusHR', 'NHDPlusHR_Superior.shp'))

#plot quickly to confirm
plot(superior['OBJECTID'])
```

The additional AOIs:

We will read in tile 1 that has been manually edited to remove the harbor area. 

```{r}
aoi1 = read_sf(file.path(shp_dir, 'tiledAOI', 'Superior_AOI_1_noharbor.shp'))
aoi2 = read_sf(file.path(shp_dir, 'tiledAOI', 'SuperiorAOI_2.shp'))
aoi3 = read_sf(file.path(shp_dir, 'tiledAOI', 'SuperiorAOI_3.shp'))
aoi4 = read_sf(file.path(shp_dir, 'tiledAOI', 'SuperiorAOI_4.shp'))
aoi5 = read_sf(file.path(shp_dir, 'tiledAOI', 'SuperiorAOI_5.shp'))

#plot quickly to confirm
plot(aoi1)
plot(aoi2)
plot(aoi3)
plot(aoi4)
plot(aoi5)
```

Merge aois into one shape (without the harbor)

```{r}
aoi <- st_union(aoi1, aoi2) %>% 
  st_union(., aoi3) %>% 
  st_union(., aoi4) %>% 
  st_union(., aoi5) %>% 
  select(rowid)

plot(aoi)
```

Save the modeling aoi.

```{r}
st_write(aoi, file.path(shp_dir, 'Superior_AOI_no_harbor.shp'))
```

