---
title: "Stacking GeoTiffs"
author: "B Steele"
date: "2023-04-07"
output: html_document
---

```{r}
library(tidyverse)
library(googledrive)

#authenticate google
drive_auth()
1 #your selection may be different

# setup python venv
source('preliminary_kmeans/pySetup.R')

# point to directories
dump_dir = 'data/prelim_kmeans/nc/'
```

```{python}
#load modules
import xarray as xr
import os
import rasterio
import rioxarray as rxr
from scipy import ndimage as ndi

# point to directories
data_dir = 'data/prelim_kmeans/unified_classes/'
```

# Purpose

This is a framework script to stack multiple geotiffs into netCDF files for the Superior Plume-Bloom project.

# Pre-work

List files, prep nc file, and write functions

```{python}
# list all files in the directory
files = os.listdir(data_dir)
files = [string for string in files if string.startswith('LAND')]

# function to get the individual years from file name
def getYear(file):
  f_list = file.split('_')
  date = f_list[2]
  year = date.split('-')[0]
  return year

#grab all years
years = *map(getYear, files),
#get unique years
years = set(years)
#save as list
years = list(years)
```

And now stack the files and save per year

```{python}
for y in enumerate(years):
  year = y[1]
  # create an empty xarray dataset to store the stacked data
  nc = xr.Dataset()
  year_files =  [file for file in files if (year in file)]
  
  # loop through the GeoTiffs and add them to the dataset
  for i, geotiff_file in enumerate(year_files):
    #get file info
    file_strings = geotiff_file.split('_')
    date = file_strings[2]
    mission = 'Landsat '+ file_strings[1]
    
    # open the GeoTiff with rasterio
    data = rxr.open_rasterio(os.path.join(data_dir, geotiff_file))
    transform = rasterio.open(os.path.join(data_dir, geotiff_file)).transform
    
    # create an xarray data array and add it to the dataset, define coords
    data_array = xr.DataArray(data,
      dims=('band', 'y', 'x'), 
      coords={'band': range(data.shape[0]), 'y': data.y, 'x': data.x})
    
    data_array.attrs['date'] = date
    data_array.attrs['mission'] = mission
    
    nc[date] = data_array
    
    #set file name
    fn = 'example_' + year + '_stack.nc'
    # save the dataset to a netCDF file
    nc.to_netcdf(os.path.join('data/prelim_kmeans/nc/', fn))

```

# Save the netCDF to drive

```{r}
drive_folder = drive_ls(pattern = 'Superior Plume-Bloom')

nc_folder = drive_ls(path = as_id(drive_folder$id), 'nc_stack', recursive = T)

nc_files = list.files(dump_dir)

uploadToDrive = function(file) {
  drive_upload(file.path(dump_dir, file),
               path = as_id(nc_folder$id),
               overwrite = T)
}

map(nc_files, uploadToDrive)
```
